# version no longer needed
services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    # strapi v3 doesn't build on arm64 yet. Hardcode to amd64 (x86_64) for now
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 3030:1337
    environment:
      - NODE_ENV=development
    # override the Dockerfile CMD for local development
    #command: npm start

